//! Artifact hierarchy — the provable outputs of the typescape.
//!
//! > "The big deal here is we render artifacts provably and reliably
//! > through typescape and AST."
//!
//! An `Artifact` is ANY deliverable produced by rendering typed AST: a file,
//! a workspace directory, a git repo, a Nix flake, a Ruby gem, an npm package,
//! a Helm chart, an OCI container image, an AMI, a Terraform module, …
//!
//! ## Taxonomy alignment
//!
//! [`ArtifactKind`] MIRRORS substrate's Nix-level `artifactKind` enum from
//! `substrate/lib/types/foundation.nix` (binary, library, service,
//! docker-image, wasm-component, wasi-service, helm-chart, npm-package, gem,
//! scaffold, overlay) and adds the higher-level pleme-io concepts the
//! typescape reasons over (workspace, repo, flake, constellation, fleet,
//! ami, store-path, terraform-module, terraform-provider).
//!
//! Adding a new `ArtifactKind` variant is a coordinated change with
//! substrate — do not silently diverge.
//!
//! ## The chain
//!
//! ```text
//! Rust types  →  typed AST (SynthesizerNode)  →  bytes  →  Artifact  →  disk / registry / cluster
//! ```
//!
//! Every artifact's `canonical_bytes()` is a deterministic encoding of its
//! file set. Hash that with BLAKE3/SHA-256 and you have a content-address.
//! Two runs of the same typescape state produce byte-identical artifacts;
//! any divergence is a proof failure, not an ambient variation.

use std::path::{Path, PathBuf};

// ─── Taxonomy ────────────────────────────────────────────────────────

/// Tag for the shape of an artifact.
///
/// The first 11 variants mirror substrate's `artifactKind` (see
/// `substrate/lib/types/foundation.nix`). The remaining variants extend
/// the taxonomy with pleme-io typescape concepts.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ArtifactKind {
    /// A single file (path + bytes). The atomic artifact.
    File,

    // ── Substrate parity ──
    /// Executable binary.
    Binary,
    /// Reusable code library (crate, lib, .a, .so).
    Library,
    /// Long-running service.
    Service,
    /// OCI container image.
    DockerImage,
    /// WebAssembly component.
    WasmComponent,
    /// WASI-compatible service.
    WasiService,
    /// Packaged Helm chart.
    HelmChart,
    /// npm package.
    NpmPackage,
    /// Ruby gem.
    Gem,
    /// Scaffold / template (skeleton files).
    Scaffold,
    /// Nix overlay.
    Overlay,

    // ── pleme-io typescape extensions ──
    /// A directory pack that represents one convergence target (e.g.,
    /// `workspaces/platform-iam/`).
    Workspace,
    /// A git repository.
    Repo,
    /// A Nix flake (repo with `flake.nix` at the root).
    Flake,
    /// A multi-workspace composition (e.g., `pangea-architectures/`).
    Constellation,
    /// A deployment fleet pack (e.g., `fleet.yaml` + workspace mapping).
    Fleet,
    /// An Amazon Machine Image (or similar baked cloud image).
    Ami,
    /// A Nix store path (already built, already cached).
    StorePath,
    /// A Terraform module.
    TerraformModule,
    /// A Terraform provider (generated by terraform-forge).
    TerraformProvider,
}

impl ArtifactKind {
    /// Stable kebab-case identifier. The first 11 variants EXACTLY match
    /// substrate's `artifactKind` enum strings — this is a grep-able
    /// attestation of taxonomy parity.
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::File => "file",
            Self::Binary => "binary",
            Self::Library => "library",
            Self::Service => "service",
            Self::DockerImage => "docker-image",
            Self::WasmComponent => "wasm-component",
            Self::WasiService => "wasi-service",
            Self::HelmChart => "helm-chart",
            Self::NpmPackage => "npm-package",
            Self::Gem => "gem",
            Self::Scaffold => "scaffold",
            Self::Overlay => "overlay",
            Self::Workspace => "workspace",
            Self::Repo => "repo",
            Self::Flake => "flake",
            Self::Constellation => "constellation",
            Self::Fleet => "fleet",
            Self::Ami => "ami",
            Self::StorePath => "store-path",
            Self::TerraformModule => "terraform-module",
            Self::TerraformProvider => "terraform-provider",
        }
    }

    /// True iff this kind is part of substrate's canonical `artifactKind`
    /// enum. Used by invariant tests to detect drift.
    #[must_use]
    pub const fn is_substrate_canonical(&self) -> bool {
        matches!(
            self,
            Self::Binary
                | Self::Library
                | Self::Service
                | Self::DockerImage
                | Self::WasmComponent
                | Self::WasiService
                | Self::HelmChart
                | Self::NpmPackage
                | Self::Gem
                | Self::Scaffold
                | Self::Overlay
        )
    }
}

/// Package ecosystems for [`Package`]-shaped artifacts.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Ecosystem {
    /// Rust crates.io / Cargo.
    Cargo,
    /// Ruby gems.
    Gem,
    /// Node.js npm.
    Npm,
    /// Python PyPI.
    Pypi,
    /// .NET NuGet.
    Nuget,
    /// Java Maven.
    Maven,
    /// Go modules.
    Go,
}

// ─── Root trait ─────────────────────────────────────────────────────

/// An artifact: any provably-rendered deliverable produced by the typescape.
///
/// Implementations MUST guarantee:
/// - [`Artifact::name`] is stable across calls.
/// - [`Artifact::kind`] is stable across calls.
/// - [`Artifact::files`] is pure: same internal state → same bytes.
///
/// The default [`Artifact::canonical_bytes`] produces a deterministic
/// encoding suitable for content-addressing.
pub trait Artifact {
    /// Canonical name of this artifact.
    fn name(&self) -> &str;

    /// Taxonomic tag.
    fn kind(&self) -> ArtifactKind;

    /// Decompose into file atoms. Every artifact ultimately materializes
    /// as files on disk or blobs in a registry.
    fn files(&self) -> Vec<FileArtifact>;

    /// Deterministic byte encoding of the file set. Callers hash this
    /// (BLAKE3, SHA-256) to content-address the artifact.
    ///
    /// This default impl sorts files by path and length-prefixes each
    /// path and blob. Byte-equal file sets → byte-equal encodings.
    fn canonical_bytes(&self) -> Vec<u8> {
        canonical_encode(&self.files())
    }
}

/// Deterministic encoding of a file set.
///
/// Algorithm: sort by path, then for each file emit
/// `len(path_bytes) ++ path_bytes ++ len(content) ++ content`, all
/// length prefixes as little-endian u64. Byte-equal file sets
/// (regardless of input ordering) → byte-equal output.
#[must_use]
pub fn canonical_encode(files: &[FileArtifact]) -> Vec<u8> {
    let mut sorted: Vec<&FileArtifact> = files.iter().collect();
    sorted.sort_by(|a, b| a.path.cmp(&b.path));

    let mut out = Vec::new();
    for f in sorted {
        let path_bytes = f.path.as_os_str().as_encoded_bytes();
        out.extend_from_slice(&(path_bytes.len() as u64).to_le_bytes());
        out.extend_from_slice(path_bytes);
        out.extend_from_slice(&(f.bytes.len() as u64).to_le_bytes());
        out.extend_from_slice(&f.bytes);
    }
    out
}

// ─── FileArtifact — the atom ─────────────────────────────────────────

/// One file: a path and its bytes. The atomic artifact.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FileArtifact {
    /// Relative or absolute path.
    pub path: PathBuf,
    /// File contents.
    pub bytes: Vec<u8>,
}

impl FileArtifact {
    /// Construct from a path and arbitrary bytes.
    #[must_use]
    pub fn new(path: impl Into<PathBuf>, bytes: impl Into<Vec<u8>>) -> Self {
        Self {
            path: path.into(),
            bytes: bytes.into(),
        }
    }

    /// Construct from a path and UTF-8 text (the common case).
    #[must_use]
    pub fn text(path: impl Into<PathBuf>, text: impl Into<String>) -> Self {
        let s: String = text.into();
        Self::new(path, s.into_bytes())
    }

    /// View bytes as UTF-8. `None` if invalid.
    #[must_use]
    pub fn as_str(&self) -> Option<&str> {
        std::str::from_utf8(&self.bytes).ok()
    }

    /// Byte length.
    #[must_use]
    pub fn len(&self) -> usize {
        self.bytes.len()
    }

    /// True when zero bytes.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.bytes.is_empty()
    }

    /// Borrow the target path.
    #[must_use]
    pub fn path(&self) -> &Path {
        &self.path
    }
}

impl Artifact for FileArtifact {
    fn name(&self) -> &str {
        self.path
            .file_name()
            .and_then(|s| s.to_str())
            .unwrap_or("")
    }

    fn kind(&self) -> ArtifactKind {
        ArtifactKind::File
    }

    fn files(&self) -> Vec<FileArtifact> {
        vec![self.clone()]
    }
}

// ─── Workspace — the directory pack ─────────────────────────────────

/// A named set of files arranged as one convergence target.
///
/// The `platform-iam/`, `platform-state/`, `platform-dns/` directory
/// shape in `pangea-architectures` is the canonical example.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Workspace {
    pub name: String,
    pub files: Vec<FileArtifact>,
}

impl Workspace {
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            files: Vec::new(),
        }
    }

    #[must_use]
    pub fn with_file(mut self, file: FileArtifact) -> Self {
        self.files.push(file);
        self
    }

    #[must_use]
    pub fn with_files(mut self, files: Vec<FileArtifact>) -> Self {
        self.files.extend(files);
        self
    }
}

impl Artifact for Workspace {
    fn name(&self) -> &str {
        &self.name
    }
    fn kind(&self) -> ArtifactKind {
        ArtifactKind::Workspace
    }
    fn files(&self) -> Vec<FileArtifact> {
        self.files.clone()
    }
}

// ─── Repo — a git repository ────────────────────────────────────────

/// A git repository artifact: name + files.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Repo {
    pub name: String,
    pub files: Vec<FileArtifact>,
}

impl Repo {
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            files: Vec::new(),
        }
    }

    #[must_use]
    pub fn with_files(mut self, files: Vec<FileArtifact>) -> Self {
        self.files.extend(files);
        self
    }
}

impl Artifact for Repo {
    fn name(&self) -> &str {
        &self.name
    }
    fn kind(&self) -> ArtifactKind {
        ArtifactKind::Repo
    }
    fn files(&self) -> Vec<FileArtifact> {
        self.files.clone()
    }
}

// ─── Flake — a Nix flake repo ───────────────────────────────────────

/// A Nix flake: a repo with `flake.nix` (and typically `flake.lock`) at
/// the root. Specialization of [`Repo`] with Nix-specific semantics.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Flake {
    pub name: String,
    pub files: Vec<FileArtifact>,
}

impl Flake {
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            files: Vec::new(),
        }
    }

    #[must_use]
    pub fn with_files(mut self, files: Vec<FileArtifact>) -> Self {
        self.files.extend(files);
        self
    }
}

impl Artifact for Flake {
    fn name(&self) -> &str {
        &self.name
    }
    fn kind(&self) -> ArtifactKind {
        ArtifactKind::Flake
    }
    fn files(&self) -> Vec<FileArtifact> {
        self.files.clone()
    }
}

// ─── Package — versioned distribution ───────────────────────────────

/// A versioned package in some language ecosystem.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Package {
    pub ecosystem: Ecosystem,
    pub name: String,
    pub version: String,
    pub files: Vec<FileArtifact>,
}

impl Package {
    #[must_use]
    pub fn new(
        ecosystem: Ecosystem,
        name: impl Into<String>,
        version: impl Into<String>,
    ) -> Self {
        Self {
            ecosystem,
            name: name.into(),
            version: version.into(),
            files: Vec::new(),
        }
    }
}

impl Artifact for Package {
    fn name(&self) -> &str {
        &self.name
    }
    fn kind(&self) -> ArtifactKind {
        match self.ecosystem {
            Ecosystem::Gem => ArtifactKind::Gem,
            Ecosystem::Npm => ArtifactKind::NpmPackage,
            Ecosystem::Cargo
            | Ecosystem::Pypi
            | Ecosystem::Nuget
            | Ecosystem::Maven
            | Ecosystem::Go => ArtifactKind::Library,
        }
    }
    fn files(&self) -> Vec<FileArtifact> {
        self.files.clone()
    }
}

// ─── Gem — specialized Ruby package ─────────────────────────────────

/// A Ruby gem. Specialization of [`Package`] called out by name since
/// pangea-* gems are a central concept in the pleme-io typescape.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Gem {
    pub name: String,
    pub version: String,
    pub files: Vec<FileArtifact>,
}

impl Gem {
    #[must_use]
    pub fn new(name: impl Into<String>, version: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            version: version.into(),
            files: Vec::new(),
        }
    }

    #[must_use]
    pub fn with_files(mut self, files: Vec<FileArtifact>) -> Self {
        self.files.extend(files);
        self
    }
}

impl Artifact for Gem {
    fn name(&self) -> &str {
        &self.name
    }
    fn kind(&self) -> ArtifactKind {
        ArtifactKind::Gem
    }
    fn files(&self) -> Vec<FileArtifact> {
        self.files.clone()
    }
}

// ─── ContainerImage — OCI image ─────────────────────────────────────

/// An OCI container image: manifest + layer blobs.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ContainerImage {
    pub name: String,
    pub tag: String,
    pub manifest: FileArtifact,
    pub layers: Vec<FileArtifact>,
}

impl ContainerImage {
    #[must_use]
    pub fn new(
        name: impl Into<String>,
        tag: impl Into<String>,
        manifest: FileArtifact,
    ) -> Self {
        Self {
            name: name.into(),
            tag: tag.into(),
            manifest,
            layers: Vec::new(),
        }
    }

    #[must_use]
    pub fn with_layer(mut self, layer: FileArtifact) -> Self {
        self.layers.push(layer);
        self
    }
}

impl Artifact for ContainerImage {
    fn name(&self) -> &str {
        &self.name
    }
    fn kind(&self) -> ArtifactKind {
        ArtifactKind::DockerImage
    }
    fn files(&self) -> Vec<FileArtifact> {
        let mut v = Vec::with_capacity(1 + self.layers.len());
        v.push(self.manifest.clone());
        v.extend(self.layers.clone());
        v
    }
}

// ─── HelmChart — packaged Helm chart ────────────────────────────────

/// A packaged Helm chart: Chart.yaml + values + templates.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HelmChart {
    pub name: String,
    pub version: String,
    pub files: Vec<FileArtifact>,
}

impl HelmChart {
    #[must_use]
    pub fn new(name: impl Into<String>, version: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            version: version.into(),
            files: Vec::new(),
        }
    }

    #[must_use]
    pub fn with_files(mut self, files: Vec<FileArtifact>) -> Self {
        self.files.extend(files);
        self
    }
}

impl Artifact for HelmChart {
    fn name(&self) -> &str {
        &self.name
    }
    fn kind(&self) -> ArtifactKind {
        ArtifactKind::HelmChart
    }
    fn files(&self) -> Vec<FileArtifact> {
        self.files.clone()
    }
}

// ─── Laws ───────────────────────────────────────────────────────────

/// Property-checkable laws for any [`Artifact`] implementation.
pub mod laws {
    use super::{canonical_encode, Artifact, FileArtifact};

    /// `canonical_bytes` is deterministic: repeated calls return the same bytes.
    #[must_use]
    pub fn canonical_bytes_deterministic<A: Artifact>(a: &A) -> bool {
        a.canonical_bytes() == a.canonical_bytes()
    }

    /// `files` is pure: repeated calls return the same file set.
    #[must_use]
    pub fn files_is_pure<A: Artifact>(a: &A) -> bool {
        a.files() == a.files()
    }

    /// `canonical_encode` is order-independent across any permutation of
    /// the input slice. Different input orderings → same output.
    #[must_use]
    pub fn canonical_encode_order_independent(a: &[FileArtifact], b: &[FileArtifact]) -> bool {
        // Precondition (caller ensures): `a` and `b` are permutations of
        // the same set. Result: canonical_encode treats them equally.
        canonical_encode(a) == canonical_encode(b)
    }

    /// `name` is stable across calls.
    #[must_use]
    pub fn name_is_stable<A: Artifact>(a: &A) -> bool {
        a.name() == a.name()
    }

    /// `kind` is stable across calls.
    #[must_use]
    pub fn kind_is_stable<A: Artifact>(a: &A) -> bool {
        a.kind() == a.kind()
    }
}

// ─── Tests ──────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // --- ArtifactKind taxonomy parity with substrate ---

    #[test]
    fn substrate_parity_binary() {
        assert_eq!(ArtifactKind::Binary.as_str(), "binary");
    }

    #[test]
    fn substrate_parity_library() {
        assert_eq!(ArtifactKind::Library.as_str(), "library");
    }

    #[test]
    fn substrate_parity_service() {
        assert_eq!(ArtifactKind::Service.as_str(), "service");
    }

    #[test]
    fn substrate_parity_docker_image() {
        assert_eq!(ArtifactKind::DockerImage.as_str(), "docker-image");
    }

    #[test]
    fn substrate_parity_wasm_component() {
        assert_eq!(ArtifactKind::WasmComponent.as_str(), "wasm-component");
    }

    #[test]
    fn substrate_parity_wasi_service() {
        assert_eq!(ArtifactKind::WasiService.as_str(), "wasi-service");
    }

    #[test]
    fn substrate_parity_helm_chart() {
        assert_eq!(ArtifactKind::HelmChart.as_str(), "helm-chart");
    }

    #[test]
    fn substrate_parity_npm_package() {
        assert_eq!(ArtifactKind::NpmPackage.as_str(), "npm-package");
    }

    #[test]
    fn substrate_parity_gem() {
        assert_eq!(ArtifactKind::Gem.as_str(), "gem");
    }

    #[test]
    fn substrate_parity_scaffold() {
        assert_eq!(ArtifactKind::Scaffold.as_str(), "scaffold");
    }

    #[test]
    fn substrate_parity_overlay() {
        assert_eq!(ArtifactKind::Overlay.as_str(), "overlay");
    }

    #[test]
    fn pleme_extensions_workspace() {
        assert_eq!(ArtifactKind::Workspace.as_str(), "workspace");
        assert!(!ArtifactKind::Workspace.is_substrate_canonical());
    }

    #[test]
    fn pleme_extensions_repo() {
        assert_eq!(ArtifactKind::Repo.as_str(), "repo");
        assert!(!ArtifactKind::Repo.is_substrate_canonical());
    }

    #[test]
    fn pleme_extensions_flake() {
        assert_eq!(ArtifactKind::Flake.as_str(), "flake");
    }

    #[test]
    fn substrate_canonical_flag_detects_parity() {
        assert!(ArtifactKind::Binary.is_substrate_canonical());
        assert!(ArtifactKind::Library.is_substrate_canonical());
        assert!(ArtifactKind::DockerImage.is_substrate_canonical());
        assert!(ArtifactKind::Gem.is_substrate_canonical());
    }

    #[test]
    fn file_atom_is_not_substrate_canonical() {
        assert!(!ArtifactKind::File.is_substrate_canonical());
    }

    // --- FileArtifact ---

    #[test]
    fn file_new_stores_path_and_bytes() {
        let a = FileArtifact::new("flake.nix", b"{}".to_vec());
        assert_eq!(a.path, PathBuf::from("flake.nix"));
        assert_eq!(a.bytes, b"{}");
    }

    #[test]
    fn file_text_stores_utf8() {
        let a = FileArtifact::text("note.txt", "hello");
        assert_eq!(a.as_str(), Some("hello"));
    }

    #[test]
    fn file_as_str_on_invalid_utf8_returns_none() {
        let a = FileArtifact::new("bin.dat", vec![0xff_u8, 0xfe, 0xfd]);
        assert_eq!(a.as_str(), None);
    }

    #[test]
    fn file_len_matches_byte_count() {
        assert_eq!(FileArtifact::text("x", "abc").len(), 3);
    }

    #[test]
    fn file_is_empty_reflects_zero_bytes() {
        assert!(FileArtifact::text("x", "").is_empty());
        assert!(!FileArtifact::text("x", "y").is_empty());
    }

    #[test]
    fn file_as_artifact_kind_is_file() {
        let a = FileArtifact::text("x", "y");
        assert_eq!(a.kind(), ArtifactKind::File);
    }

    #[test]
    fn file_as_artifact_name_is_basename() {
        let a = FileArtifact::text("workspaces/iam/flake.nix", "{}");
        assert_eq!(Artifact::name(&a), "flake.nix");
    }

    #[test]
    fn file_as_artifact_files_is_singleton() {
        let a = FileArtifact::text("x", "y");
        assert_eq!(a.files().len(), 1);
    }

    // --- Workspace ---

    #[test]
    fn workspace_new_is_empty() {
        let w = Workspace::new("platform-iam");
        assert_eq!(Artifact::name(&w), "platform-iam");
        assert!(w.files.is_empty());
    }

    #[test]
    fn workspace_with_file_accumulates() {
        let w = Workspace::new("platform-iam")
            .with_file(FileArtifact::text("flake.nix", "{}"))
            .with_file(FileArtifact::text("pangea.yml", "---"));
        assert_eq!(w.files.len(), 2);
    }

    #[test]
    fn workspace_kind_is_workspace() {
        let w = Workspace::new("x");
        assert_eq!(w.kind(), ArtifactKind::Workspace);
    }

    #[test]
    fn workspace_files_exposes_all() {
        let w = Workspace::new("platform-iam")
            .with_files(vec![
                FileArtifact::text("a", "1"),
                FileArtifact::text("b", "2"),
                FileArtifact::text("c", "3"),
            ]);
        assert_eq!(w.files().len(), 3);
    }

    // --- Repo ---

    #[test]
    fn repo_new_is_empty() {
        let r = Repo::new("synthesizer-core");
        assert_eq!(r.name, "synthesizer-core");
        assert!(r.files.is_empty());
    }

    #[test]
    fn repo_kind_is_repo() {
        assert_eq!(Repo::new("x").kind(), ArtifactKind::Repo);
    }

    #[test]
    fn repo_with_files_accumulates() {
        let r = Repo::new("x").with_files(vec![
            FileArtifact::text("Cargo.toml", "[package]"),
            FileArtifact::text("src/lib.rs", "pub fn x() {}"),
        ]);
        assert_eq!(r.files().len(), 2);
    }

    // --- Flake ---

    #[test]
    fn flake_kind_is_flake() {
        assert_eq!(Flake::new("x").kind(), ArtifactKind::Flake);
    }

    #[test]
    fn flake_carries_flake_nix() {
        let f = Flake::new("meimei").with_files(vec![
            FileArtifact::text("flake.nix", "{ outputs = ..."),
            FileArtifact::text("flake.lock", "{}"),
        ]);
        assert_eq!(f.files().len(), 2);
    }

    // --- Package ---

    #[test]
    fn package_gem_ecosystem_maps_to_gem_kind() {
        let p = Package::new(Ecosystem::Gem, "pangea-core", "1.0.0");
        assert_eq!(p.kind(), ArtifactKind::Gem);
    }

    #[test]
    fn package_npm_ecosystem_maps_to_npm_kind() {
        let p = Package::new(Ecosystem::Npm, "@pleme/foo", "0.1.0");
        assert_eq!(p.kind(), ArtifactKind::NpmPackage);
    }

    #[test]
    fn package_cargo_ecosystem_maps_to_library_kind() {
        let p = Package::new(Ecosystem::Cargo, "synthesizer-core", "0.1.0");
        assert_eq!(p.kind(), ArtifactKind::Library);
    }

    #[test]
    fn package_pypi_ecosystem_maps_to_library_kind() {
        let p = Package::new(Ecosystem::Pypi, "foo", "1.0.0");
        assert_eq!(p.kind(), ArtifactKind::Library);
    }

    // --- Gem ---

    #[test]
    fn gem_kind_is_gem() {
        assert_eq!(Gem::new("pangea-core", "1.0.0").kind(), ArtifactKind::Gem);
    }

    #[test]
    fn gem_carries_name_and_version() {
        let g = Gem::new("pangea-aws", "2.3.1");
        assert_eq!(g.name, "pangea-aws");
        assert_eq!(g.version, "2.3.1");
    }

    // --- ContainerImage ---

    #[test]
    fn container_image_kind_is_docker_image() {
        let img = ContainerImage::new(
            "ghcr.io/pleme-io/x",
            "0.1.0",
            FileArtifact::text("manifest.json", "{}"),
        );
        assert_eq!(img.kind(), ArtifactKind::DockerImage);
    }

    #[test]
    fn container_image_files_includes_manifest_and_layers() {
        let img = ContainerImage::new(
            "x",
            "v1",
            FileArtifact::text("manifest.json", "{}"),
        )
        .with_layer(FileArtifact::new("layer0.tar", vec![0_u8; 64]))
        .with_layer(FileArtifact::new("layer1.tar", vec![1_u8; 64]));
        assert_eq!(img.files().len(), 3);
    }

    #[test]
    fn container_image_layers_appended_in_order() {
        let img = ContainerImage::new(
            "x",
            "v1",
            FileArtifact::text("m", "m"),
        )
        .with_layer(FileArtifact::text("L0", "a"))
        .with_layer(FileArtifact::text("L1", "b"));
        let files = img.files();
        assert_eq!(files[0].as_str(), Some("m"));
        assert_eq!(files[1].as_str(), Some("a"));
        assert_eq!(files[2].as_str(), Some("b"));
    }

    // --- HelmChart ---

    #[test]
    fn helm_chart_kind_is_helm_chart() {
        assert_eq!(
            HelmChart::new("pleme-vector", "0.2.8").kind(),
            ArtifactKind::HelmChart
        );
    }

    #[test]
    fn helm_chart_carries_files() {
        let c = HelmChart::new("x", "1.0.0").with_files(vec![
            FileArtifact::text("Chart.yaml", "name: x"),
            FileArtifact::text("values.yaml", "foo: bar"),
        ]);
        assert_eq!(c.files().len(), 2);
    }

    // --- canonical_encode ---

    #[test]
    fn canonical_encode_empty_is_empty() {
        assert_eq!(canonical_encode(&[]), Vec::<u8>::new());
    }

    #[test]
    fn canonical_encode_deterministic() {
        let files = vec![
            FileArtifact::text("a", "hello"),
            FileArtifact::text("b", "world"),
        ];
        assert_eq!(canonical_encode(&files), canonical_encode(&files));
    }

    #[test]
    fn canonical_encode_order_independent() {
        let f1 = FileArtifact::text("alpha", "A");
        let f2 = FileArtifact::text("beta", "B");
        let f3 = FileArtifact::text("gamma", "C");

        let forward = vec![f1.clone(), f2.clone(), f3.clone()];
        let reverse = vec![f3, f2, f1];

        assert_eq!(canonical_encode(&forward), canonical_encode(&reverse));
    }

    #[test]
    fn canonical_encode_distinguishes_distinct_contents() {
        let a = vec![FileArtifact::text("x", "one")];
        let b = vec![FileArtifact::text("x", "two")];
        assert_ne!(canonical_encode(&a), canonical_encode(&b));
    }

    #[test]
    fn canonical_encode_distinguishes_distinct_paths() {
        let a = vec![FileArtifact::text("x", "same")];
        let b = vec![FileArtifact::text("y", "same")];
        assert_ne!(canonical_encode(&a), canonical_encode(&b));
    }

    // --- Laws ---

    #[test]
    fn law_canonical_bytes_deterministic_holds_on_workspace() {
        let w = Workspace::new("platform-iam").with_file(FileArtifact::text("f", "body"));
        assert!(laws::canonical_bytes_deterministic(&w));
    }

    #[test]
    fn law_files_is_pure_holds_on_repo() {
        let r = Repo::new("x")
            .with_files(vec![FileArtifact::text("Cargo.toml", "[package]")]);
        assert!(laws::files_is_pure(&r));
    }

    #[test]
    fn law_canonical_encode_order_independent_holds() {
        let files_a = vec![
            FileArtifact::text("b", "2"),
            FileArtifact::text("a", "1"),
        ];
        let files_b = vec![
            FileArtifact::text("a", "1"),
            FileArtifact::text("b", "2"),
        ];
        assert!(laws::canonical_encode_order_independent(&files_a, &files_b));
    }

    #[test]
    fn law_name_is_stable_on_gem() {
        let g = Gem::new("pangea-aws", "1.0.0");
        assert!(laws::name_is_stable(&g));
    }

    #[test]
    fn law_kind_is_stable_on_container_image() {
        let img = ContainerImage::new("x", "v", FileArtifact::text("m", ""));
        assert!(laws::kind_is_stable(&img));
    }

    // --- Equality / Clone plumbing ---

    #[test]
    fn equal_workspaces_compare_equal() {
        let a = Workspace::new("x").with_file(FileArtifact::text("f", "body"));
        let b = Workspace::new("x").with_file(FileArtifact::text("f", "body"));
        assert_eq!(a, b);
    }

    #[test]
    fn differing_workspaces_compare_unequal() {
        let a = Workspace::new("x");
        let b = Workspace::new("y");
        assert_ne!(a, b);
    }

    #[test]
    fn clone_workspace_produces_equal() {
        let w = Workspace::new("x").with_file(FileArtifact::text("f", "body"));
        let w2 = w.clone();
        assert_eq!(w, w2);
    }

    // --- Property tests ---

    proptest::proptest! {
        #[test]
        fn prop_canonical_bytes_deterministic_any_workspace(
            name in "[a-z]{1,10}",
            files in proptest::collection::vec(("[a-z]{1,5}", "[a-z]{0,20}"), 0..10)
        ) {
            let ws = Workspace::new(name).with_files(
                files.into_iter().map(|(p, b)| FileArtifact::text(p, b)).collect()
            );
            proptest::prop_assert!(laws::canonical_bytes_deterministic(&ws));
        }

        #[test]
        fn prop_file_set_reorder_yields_same_encoding(
            files in proptest::collection::vec(("[a-z]{1,8}", "[a-z]{0,10}"), 1..8)
        ) {
            // Deduplicate paths so reordering is meaningful.
            let mut seen = std::collections::HashSet::new();
            let unique: Vec<FileArtifact> = files.into_iter()
                .filter(|(p, _)| seen.insert(p.clone()))
                .map(|(p, b)| FileArtifact::text(p, b))
                .collect();

            let mut reversed = unique.clone();
            reversed.reverse();

            proptest::prop_assert_eq!(
                canonical_encode(&unique),
                canonical_encode(&reversed)
            );
        }
    }
}
